[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Backend-Server = "AWS-S3-Alpha"
    X-Load-Balancer = "CloudXNS-GeoDNS"
    X-GSLB = "CDN-Netlify"
    Access-Control-Allow-Origin = "*"
	Cache-Control = "public, max-age=691200, s-max-age=10368000, must-revalidate"
