[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Backend-Server = "AWS-S3-Alpha"
    X-Load-Balancer = "CloudXNS-GeoDNS"
    X-GSLB = "CDN-Netlify"
    Accee-Allow-Origin = "*"
